### ISSUE TITLE
Game stucks at the moment of downloading the profile from the server. Is it offline?

### ISSUE THREAD

**Issue by Enh4** [pumpitupdev/pumpnet-feedback#4]
I tried to play NX2 and NXA again a week ago, and I'm not able to pass through the USB Connection screen. Looking into the console the last thing I can read is something about getting the save file from server. But nothing happens, and it gets stuck right there.
I assume the server is offline, so the game is not able to retrieve the information. I didn't change anything else from the last time I played  the game properly.

Now I can only play with offline generic usb profile, which for some reason causes random freezes while playing (mostly on world max) and I'm not sure if that's a problem from the game or if it's my computer, but again, nothing strange happened to it.

**Comment by voidderef** [comment]
Hey, thanks for reaching out regarding that. I have been quite busy with other things that are unfortunately higher in regards of priority, so the whole project didn't get a lot of attention and love for quite a while.

But, I had some spare time and energy to look at the server side of things today an noticed some parts being unhealthy for unknown reasons. Some manual maintenance and looks more healthy now from an infrastructure side.

Can you test and confirm that you can connect to the server again?

> Now I can only play with offline generic usb profile, which for some reason causes random freezes while playing (mostly on world max) and I'm not sure if that's a problem from the game or if it's my computer, but again, nothing strange happened to it.

Kinda hard to tell just by the symptoms of it. Can you provide a redacted (removed username, IDs, credentials) log output from the game when that happens?

**Comment by Enh4** [comment]
Hello again, sorry I've been off for a week... I'll give it a try tonight ! Thanks for checking! 

> Kinda hard to tell just by the symptoms of it. Can you provide a redacted (removed username, IDs, credentials) log output from the game when that happens?

I'm pretty noob when it comes to linux (I've learned the basic for running the games). I'm not quite sure on how to create the log output so I can share it with you

**Comment by Enh4** [comment]
I have tested the game, and it's working properly now. My profile is working just fine, and at least the couple credits I played last night, I had 0 freezes.

My theory is that the freezes had something to do with the usb writing or something... Am I right when I say that when the profile is connected to the server, the writing and reading is only made at certain points of the game? While when it comes to local usb profile, the writing and reading is something that happens constantly? 

I only had the freezing or lagging issues while the local usb connection was on. There was no freezing while playing without usb profile.

**Comment by icex2** [comment]
> I have tested the game, and it's working properly now. My profile is working just fine, and at least the couple credits I played last night, I had 0 freezes.

That's great to hear, thanks for your feedback.

> My theory is that the freezes had something to do with the usb writing or something... Am I right when I say that when the profile is connected to the server, the writing and reading is only made at certain points of the game? While when it comes to local usb profile, the writing and reading is something that happens constantly?

The network calls to the server are fully blocking. If they cannot reach the server, they will block and freeze the entire game when trying to read/write the USB profile. That's due to the design of the rather complex feature of hacking up the file reads/writes and re-directing them over a network connection with the current implementation.

Reading and writing the profile only happens on the profile screen, never during gameplay.

> I only had the freezing or lagging issues while the local usb connection was on. There was no freezing while playing without usb profile.

That's interesting. I haven't seen that happening thus far. Might be a separate issue then that needs further debugging to understand what's going on. But, to manage expectations, I won't likely have the capacity to look into that myself in the near future. Though I am happy to provide some pointers and support where to get started if you or someone else is interested in looking into this.

**Comment by Enh4** [comment]
> That's great to hear, thanks for your feedback.

No problem! thank you for fixing it! 

> Reading and writing the profile only happens on the profile screen, never during gameplay.

Does it happens also when you use your mileage ingame? i.e World Max, or Special Zone? because when I use it for some helper or unlock, it does freeze the game for a little.

> That's interesting. I haven't seen that happening thus far. Might be a separate issue then that needs further debugging to understand what's going on. But, to manage expectations, I won't likely have the capacity to look into that myself in the near future. Though I am happy to provide some pointers and support where to get started if you or someone else is interested in looking into this.

I would love to contribute more to the project since I love this game, but sadly I have zero to none knowledge in coding, and I have a bad time configuring linux to be able on running the game at first... still I know the basics to run the mixes.

I'll still wait until the day Fiesta Series are available for testing :) really looking forward to playing those mixes! Thanks for all the job you made so far!

**Comment by voidderef** [comment]
> Does it happens also when you use your mileage ingame? i.e World Max, or Special Zone? because when I use it for some helper or unlock, it does freeze the game for a little.

I don't know for sure, but I consider it possible because it might write the resulting mileage immediately back to the save file in order to avoid longer periods of data inconsistency with what's stored on the thumb drive.

> I would love to contribute more to the project since I love this game, but sadly I have zero to none knowledge in coding, and I have a bad time configuring linux to be able on running the game at first... still I know the basics to run the mixes.

No worries. I just keep asking/reaching out to people as the project would highly benefit from more support that I currently cannot offer.

> I'll still wait until the day Fiesta Series are available for testing :) really looking forward to playing those mixes! Thanks for all the job you made so far!

Yeah, sorry for keeping you and everyone else waiting. I cannot give any ETAs regarding that because it's not high up on my priority list and I cannot tell when I got the capacity and energy to get to that.
